name: Deploy Staging

on:
  push:
    branches:
      - main
    paths:
      - 'steamphony-api/**'
      - 'Steam web/**'
      - 'docker-compose.yml'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_KEY }}

      - name: Copy project to server
        run: |
          rsync -av --delete ./ ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }}:${{ secrets.STAGING_PATH }}

      - name: Deploy via docker-compose
        run: |
          ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_HOST }} "cd ${{ secrets.STAGING_PATH }}/steamphony-api && docker-compose pull && docker-compose up -d --remove-orphans" 